name: Build and Deploy to Cloudflare Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   name: Install dependencies
                run: npm install
                env:
                    BLOGGRIFY_EPOXIA_LICENSE: ${{ secrets.BLOGGRIFY_EPOXIA_LICENSE }}

            # Add debugging steps
            -   name: Debug package installation
                run: |
                    echo "Package.json content:"
                    cat package.json
                    echo "\nChecking @bloggrify/epoxia in node_modules:"
                    ls -la node_modules/@bloggrify/epoxia || echo "Directory not found"
                    echo "\nNPM list for @bloggrify/epoxia:"
                    npm ls @bloggrify/epoxia
                    echo "\nPackage contents:"
                    ls -R node_modules/@bloggrify/epoxia || echo "Cannot list contents"

            -   name: Setup theme components
                run: |
                    mkdir -p components/themes/epoxia
                    ln -s ../../../node_modules/@bloggrify/epoxia/components/content/EpoxiaHeroSection.vue components/themes/epoxia/HeroSection.vue
                    ln -s ../../../node_modules/@bloggrify/epoxia/components/content/EpoxiaNewsletterForm.vue components/themes/epoxia/NewsletterForm.vue

            - name: Install Playwright
              run: npm install -D @playwright/test@latest

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            -   name: Build Nuxt project
                run: npm run generate
                env:
                    BLOGGRIFY_EPOXIA_LICENSE: ${{ secrets.BLOGGRIFY_EPOXIA_LICENSE }}

            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                projectName: blog  # Replace with your Cloudflare Pages project name
                directory: dist
                # Optional: Add a specific branch name
                branch: main
